// MCQ Bank — Updated with 10+ questions per subject
const MCQ = {
  "Programming Principles with C":[
    {q:"Which syntax declares a pointer in C?",opts:["int *p;","int &p;","pointer int p;","int ^p;"],ans:0,exp:"int *p; declares p as a pointer to int."},
    {q:"printf('%d', sizeof(int)) depends on:",opts:["OS","Compiler","RAM","None"],ans:1,exp:"sizeof(int) is compiler/platform dependent."},
    {q:"Header file for standard I/O in C:",opts:["stdlib.h","conio.h","stdio.h","string.h"],ans:2,exp:"stdio.h provides printf, scanf, etc."},
    {q:"'break' statement in a loop:",opts:["Skips iteration","Exits loop","Restarts loop","Syntax error"],ans:1,exp:"break exits the nearest loop."},
    {q:"Storage class that retains value between calls:",opts:["auto","register","extern","static"],ans:3,exp:"static retains value between function calls."},
    {q:"'malloc' does:",opts:["Deallocates memory","Static allocation","Dynamic allocation","Initializes to zero"],ans:2,exp:"malloc() allocates dynamic memory at runtime."},
    {q:"Which loop executes at least once?",opts:["for","while","do-while","None"],ans:2,exp:"do-while checks condition after body."},
    {q:"Operator to access structure via pointer:",opts:[".",":","->","::"],ans:2,exp:"-> accesses structure members through pointer."},
    {q:"NULL pointer points to:",opts:["Address 0","Random address","Last address","Nothing/invalid"],ans:3,exp:"NULL pointer doesn't point to valid memory."},
    {q:"2D array declaration in C:",opts:["int arr[3,3];","int arr[3][3];","int arr(3)(3);","int[3][3] arr;"],ans:1,exp:"int arr[3][3]; is correct syntax."},
    {q:"Function to free dynamic memory:",opts:["delete()","remove()","free()","clear()"],ans:2,exp:"free() releases dynamically allocated memory."},
  ],
  "Digital Logic and Applications":[
    {q:"Gate with output 1 only when all inputs are 1:",opts:["OR","AND","NOT","XOR"],ans:1,exp:"AND gate: output 1 only when ALL inputs are 1."},
    {q:"Complement of A in Boolean algebra:",opts:["A'","A+1","A*0","2A"],ans:0,exp:"A' (A prime) is the complement of A."},
    {q:"Number system with base 16:",opts:["Binary","Octal","Decimal","Hexadecimal"],ans:3,exp:"Hexadecimal base = 16."},
    {q:"Binary 1010 in decimal:",opts:["8","10","12","14"],ans:1,exp:"1010 = 8+0+2+0 = 10."},
    {q:"XOR gives 1 when:",opts:["Both 1","Both 0","Inputs differ","Both same"],ans:2,exp:"XOR = 1 when inputs are different."},
    {q:"Flip-flop stores:",opts:["4 bits","2 bits","1 bit","8 bits"],ans:2,exp:"Flip-flop is a 1-bit memory."},
    {q:"Universal gate:",opts:["AND","OR","NAND","XOR"],ans:2,exp:"NAND is universal gate."},
    {q:"De Morgan's (A.B)' =",opts:["A'.B'","A'+B'","A.B","A'+B"],ans:1,exp:"(A.B)' = A' + B'"},
    {q:"Half adder outputs:",opts:["1","2","3","4"],ans:1,exp:"Half adder: Sum and Carry — 2 outputs."},
    {q:"Sequential circuit example:",opts:["AND gate","Multiplexer","Flip-flop","Decoder"],ans:2,exp:"Flip-flop is sequential."},
    {q:"2's complement of 0110:",opts:["1001","1010","1110","0110"],ans:1,exp:"1's complement = 1001, +1 = 1010."},
  ],
  "Fundamentals of Database Management Systems":[
    {q:"DBMS stands for:",opts:["Data Backup Management System","Database Management System","Data Binary Management","Digital Base Management"],ans:1,exp:"DBMS = Database Management System."},
    {q:"Key that uniquely identifies each record:",opts:["Foreign Key","Candidate Key","Primary Key","Super Key"],ans:2,exp:"Primary Key uniquely identifies records."},
    {q:"SQL stands for:",opts:["Structured Query Language","Simple Query Logic","Standard Query Layer","System Query Language"],ans:0,exp:"SQL = Structured Query Language."},
    {q:"Command to retrieve data in SQL:",opts:["INSERT","UPDATE","SELECT","DELETE"],ans:2,exp:"SELECT retrieves data."},
    {q:"Relationship maintained through:",opts:["Primary Key","Foreign Key","Index","View"],ans:1,exp:"Foreign Key maintains referential integrity."},
    {q:"DDL command:",opts:["INSERT","SELECT","CREATE","UPDATE"],ans:2,exp:"CREATE is DDL command."},
    {q:"Normalization reduces:",opts:["Queries","Redundancy","Columns","Rows"],ans:1,exp:"Normalization reduces data redundancy."},
    {q:"ER stands for:",opts:["Entity Relation","Entity Relationship","External Reference","Entity Record"],ans:1,exp:"ER = Entity-Relationship."},
    {q:"DML stands for:",opts:["Data Manipulation Language","Data Management Logic","Digital Manipulation","Data Modelling"],ans:0,exp:"DML = Data Manipulation Language."},
    {q:"NOT a property of relational DB:",opts:["Tables","Rows","Pointers","Columns"],ans:2,exp:"Relational DB uses tables, not pointers."},
    {q:"ACID stands for:",opts:["Atomicity Consistency Isolation Durability","Auto Control Index Data","None","Atomicity Control Isolation Data"],ans:0,exp:"ACID = Atomicity, Consistency, Isolation, Durability."},
  ],
  "Computational Logic and Discrete Structure":[
    {q:"Proposition is a statement that is:",opts:["Always true","Always false","Either true or false","Neither"],ans:2,exp:"Proposition has definite truth value."},
    {q:"Tautology:",opts:["p AND q","p OR q","p OR (NOT p)","p AND (NOT p)"],ans:2,exp:"p OR NOT p is always true."},
    {q:"Contrapositive of 'If P then Q':",opts:["If Q then P","If not P then not Q","If not Q then not P","If P then not Q"],ans:2,exp:"Contrapositive: NOT Q → NOT P."},
    {q:"Set with no elements:",opts:["Universal set","Null set","Singleton set","Power set"],ans:1,exp:"Null/Empty set has no elements."},
    {q:"Subsets of set with n elements:",opts:["n","2n","2^n","n^2"],ans:2,exp:"2^n subsets."},
    {q:"Graph with no cycles is called:",opts:["Directed graph","Tree","Complete graph","Bipartite"],ans:1,exp:"Connected acyclic graph = Tree."},
    {q:"GCD(12,8) = ?",opts:["2","4","6","8"],ans:1,exp:"GCD(12,8) = 4."},
    {q:"f(x)=x+2, g(x)=2x, f(g(3))=?",opts:["8","10","7","6"],ans:0,exp:"g(3)=6, f(6)=8."},
    {q:"Symmetric relation: aRb implies:",opts:["bRa","aRa","aRc","None"],ans:0,exp:"Symmetric: aRb implies bRa."},
    {q:"NOT a valid proof technique:",opts:["Direct proof","Proof by contradiction","Proof by example","Proof by induction"],ans:2,exp:"Single example doesn't prove universal statement."},
    {q:"Logical AND of 1 and 0:",opts:["1","0","Undefined","2"],ans:1,exp:"1 AND 0 = 0."},
  ],
  "Communication Skills":[
    {q:"Example of non-verbal communication:",opts:["Email","Body language","Phone call","Written report"],ans:1,exp:"Body language is non-verbal."},
    {q:"7 C's of communication do NOT include:",opts:["Clarity","Conciseness","Confusion","Completeness"],ans:2,exp:"Confusion is not one of the 7 C's."},
    {q:"Listening style focused on feelings:",opts:["Active","Passive","Empathic","Critical"],ans:2,exp:"Empathic listening focuses on feelings."},
    {q:"Formal written communication within organization:",opts:["Memo","Letter","Notice","Report"],ans:0,exp:"Memo is formal internal communication."},
    {q:"Upward communication flows:",opts:["Manager to employee","Employee to manager","Same level","External"],ans:1,exp:"Upward = subordinate to superior."},
    {q:"Barrier to communication:",opts:["Clear message","Good feedback","Noise","Eye contact"],ans:2,exp:"Noise is a communication barrier."},
    {q:"Primary purpose of resume:",opts:["Tell life story","Get job interview","List all achievements","Describe personality"],ans:1,exp:"Resume secures a job interview."},
    {q:"SQ3R reading method:",opts:["Survey Question Read Recite Review","See Question Read Record Review","Survey Quick Read Recite Recall","None"],ans:0,exp:"SQ3R = Survey, Question, Read, Recite, Review."},
    {q:"Group discussion requires:",opts:["One speaker","Active participation by all","Written format","Formal attire"],ans:1,exp:"GD needs active participation from all."},
    {q:"Reading from notes in presentation is:",opts:["Encouraged","Acceptable","Discouraged","Mandatory"],ans:2,exp:"Reading from notes reduces engagement — discouraged."},
  ],
  "Fundamentals of Microprocessors & Microcontrollers":[
    {q:"8085 data bus width:",opts:["4-bit","8-bit","16-bit","32-bit"],ans:1,exp:"8085 has 8-bit data bus."},
    {q:"Register storing arithmetic results:",opts:["B register","PC","Accumulator","SP"],ans:2,exp:"Accumulator stores arithmetic/logical results."},
    {q:"ALU stands for:",opts:["Arithmetic Logic Unit","Array Logic Unit","Arithmetic Level Unit","None"],ans:0,exp:"ALU = Arithmetic Logic Unit."},
    {q:"Program Counter stores:",opts:["Current data","Next instruction address","Operation result","Stack address"],ans:1,exp:"PC = address of next instruction."},
    {q:"8051 has how many I/O ports:",opts:["2","4","6","8"],ans:1,exp:"8051 has 4 I/O ports (P0-P3)."},
    {q:"Immediate addressing uses operand:",opts:["From register","Directly in instruction","From memory","From stack"],ans:1,exp:"Immediate addressing: operand in instruction itself."},
    {q:"ALE in 8085 stands for:",opts:["Address Latch Enable","Arithmetic Logic Enable","Address Level Enable","None"],ans:0,exp:"ALE = Address Latch Enable."},
    {q:"Highest priority interrupt in 8085:",opts:["INTR","RST 5.5","RST 6.5","TRAP"],ans:3,exp:"TRAP has highest priority (non-maskable)."},
    {q:"8085 address bus width:",opts:["8-bit","12-bit","16-bit","20-bit"],ans:2,exp:"8085 has 16-bit address bus."},
    {q:"XCHG instruction exchanges:",opts:["A and B","HL and DE","BC and DE","SP and HL"],ans:1,exp:"XCHG exchanges HL and DE registers."},
  ],
  "Web Applications Development":[
    {q:"HTML stands for:",opts:["Hyper Text Markup Language","High Text Making Language","Hyper Transfer Markup","Hyper Text Making Logic"],ans:0,exp:"HTML = HyperText Markup Language."},
    {q:"Tag that creates a hyperlink:",opts:["<link>","<href>","<a>","<url>"],ans:2,exp:"<a href='url'> creates hyperlink."},
    {q:"CSS stands for:",opts:["Computer Style Sheets","Colorful Style Sheets","Cascading Style Sheets","Creative Style Sheets"],ans:2,exp:"CSS = Cascading Style Sheets."},
    {q:"CSS property for text color:",opts:["font-color","text-color","color","foreground"],ans:2,exp:"'color' property changes text color."},
    {q:"JavaScript is:",opts:["Compiled","Server-side only","Client-side scripting","Machine level"],ans:2,exp:"JavaScript is client-side scripting language."},
    {q:"Largest heading tag:",opts:["<h6>","<head>","<h1>","<heading>"],ans:2,exp:"<h1> is largest heading."},
    {q:"HTTP stands for:",opts:["Hyper Text Transfer Protocol","High Transfer Text","Hyper Text Transport","High Text Transfer"],ans:0,exp:"HTTP = HyperText Transfer Protocol."},
    {q:"Image source attribute:",opts:["href","link","src","url"],ans:2,exp:"src specifies image source."},
    {q:"Tag for unordered list:",opts:["<ol>","<ul>","<li>","<list>"],ans:1,exp:"<ul> = unordered list."},
    {q:"CSS box model includes:",opts:["Content only","Content border","Content padding border margin","Content margin"],ans:2,exp:"Box model = Content + Padding + Border + Margin."},
    {q:"To make text bold in HTML:",opts:["<i>","<u>","<b>","<em>"],ans:2,exp:"<b> makes text bold."},
  ],
  "Numerical Methods":[
    {q:"Bisection method requires:",opts:["f(a)*f(b)>0","f(a)*f(b)<0","f(a)=f(b)","f(a)=0"],ans:1,exp:"Bisection needs f(a)*f(b)<0."},
    {q:"Newton-Raphson convergence:",opts:["Linear","Quadratic","Cubic","None"],ans:1,exp:"Newton-Raphson converges quadratically."},
    {q:"Trapezoidal rule is used for:",opts:["Solving equations","Numerical integration","Matrix ops","Interpolation"],ans:1,exp:"Trapezoidal rule = numerical integration."},
    {q:"Lagrange interpolation estimates:",opts:["Differential equations","Values between known points","Eigenvalues","None"],ans:1,exp:"Lagrange interpolates between known data points."},
    {q:"Gaussian elimination solves:",opts:["Differential equations","Linear equations","Integrals","Eigenvalues"],ans:1,exp:"Gaussian elimination solves linear systems."},
    {q:"Error = True value minus:",opts:["Exact value","Approximate value","Zero","Infinity"],ans:1,exp:"Error = True - Approximate value."},
    {q:"Fastest converging method:",opts:["Bisection","False Position","Newton-Raphson","Secant"],ans:2,exp:"Newton-Raphson is fastest."},
    {q:"Simpson's 1/3 rule needs:",opts:["Odd intervals","Even intervals","Any intervals","Exactly 3"],ans:1,exp:"Simpson's 1/3 needs even number of intervals."},
    {q:"Round-off error due to:",opts:["Wrong formula","Finite digit representation","Algorithm","None"],ans:1,exp:"Round-off from finite digit arithmetic."},
    {q:"LU decomposition: A = ?",opts:["L+U","L*U","L-U","L/U"],ans:1,exp:"A = L * U (Lower * Upper triangular)."},
  ],
  "Object Oriented Programming":[
    {q:"OOP concept allowing property inheritance:",opts:["Polymorphism","Encapsulation","Inheritance","Abstraction"],ans:2,exp:"Inheritance allows child class to inherit from parent."},
    {q:"Encapsulation means:",opts:["Multiple objects","Hiding data inside class","Overloading operators","Subclasses"],ans:1,exp:"Encapsulation hides data and methods."},
    {q:"'One interface many implementations':",opts:["Inheritance","Encapsulation","Abstraction","Polymorphism"],ans:3,exp:"Polymorphism = one interface, multiple implementations."},
    {q:"Constructor is called:",opts:["Manually","Automatically on object creation","Once only","At end"],ans:1,exp:"Constructor auto-called on object instantiation."},
    {q:"Abstract class:",opts:["Can be instantiated","Cannot be instantiated","No methods","No variables"],ans:1,exp:"Abstract class cannot be instantiated."},
    {q:"Method overloading = same name with:",opts:["Different parameters","Same parameters","Different body","None"],ans:0,exp:"Overloading = same name, different parameters."},
    {q:"'this' keyword refers to:",opts:["Parent class","Current object","Static method","Return type"],ans:1,exp:"'this' = current object."},
    {q:"Interface contains:",opts:["Full implementations","Only declarations","Private variables","Constructors"],ans:1,exp:"Interface has only method declarations."},
    {q:"NOT a pillar of OOP:",opts:["Inheritance","Polymorphism","Compilation","Encapsulation"],ans:2,exp:"4 pillars: Inheritance, Polymorphism, Encapsulation, Abstraction."},
    {q:"Destructor is used to:",opts:["Create object","Cleanup/destroy object","Copy object","Compare"],ans:1,exp:"Destructor frees resources."},
  ],
  "Green Computing":[
    {q:"Green computing aims to:",opts:["Increase power usage","Reduce environmental impact","Increase production","None"],ans:1,exp:"Green computing reduces environmental impact of IT."},
    {q:"E-waste refers to:",opts:["Electronic waste","Energy waste","Environmental waste","None"],ans:0,exp:"E-waste = discarded electronic equipment."},
    {q:"Green computing practice:",opts:["Always-on computers","Virtualization","Buy hardware often","Print all documents"],ans:1,exp:"Virtualization reduces hardware needs."},
    {q:"Cloud computing helps green computing by:",opts:["More servers","Resource sharing/efficiency","More hardware","Higher costs"],ans:1,exp:"Cloud enables resource sharing."},
    {q:"PUE measures:",opts:["CPU speed","Data center energy efficiency","Battery life","Network speed"],ans:1,exp:"PUE = Power Usage Effectiveness."},
    {q:"Energy Star is:",opts:["ISO 9001","Energy-efficient product certification","CMMI","IEEE"],ans:1,exp:"Energy Star = US EPA energy efficiency certification."},
    {q:"Virtualization reduces:",opts:["Software costs","Physical servers and energy","Internet speed","Data loss"],ans:1,exp:"Virtualization reduces physical servers."},
    {q:"Carbon footprint reduced by:",opts:["More devices","Remote working","More printing","Longer hours"],ans:1,exp:"Remote working reduces energy consumption."},
    {q:"NOT a benefit of green computing:",opts:["Lower bills","Less e-waste","Higher electricity","Better environment"],ans:2,exp:"Green computing REDUCES electricity usage."},
    {q:"RoHS restricts:",opts:["Software","Hazardous substances in electronics","Network protocols","Data storage"],ans:1,exp:"RoHS restricts hazardous substances in electronics."},
  ],
  "Python Programming":[
    {q:"Keyword to create a function:",opts:["func","function","def","define"],ans:2,exp:"'def' defines a function."},
    {q:"type([]) returns:",opts:["<class 'tuple'>","<class 'list'>","<class 'array'>","<class 'set'>"],ans:1,exp:"[] is a list."},
    {q:"IMMUTABLE in Python:",opts:["List","Dictionary","Tuple","Set"],ans:2,exp:"Tuples are immutable."},
    {q:"len('Mumbai') =",opts:["5","6","7","Error"],ans:1,exp:"'Mumbai' = 6 characters."},
    {q:"Floor division operator:",opts:["/","//","%","**"],ans:1,exp:"// = floor division."},
    {q:"Open file for reading:",opts:["open('f','w')","open('f','r')","open('f','a')","open('f','x')"],ans:1,exp:"'r' mode = read."},
    {q:"Uses key-value pairs:",opts:["List","Tuple","Set","Dictionary"],ans:3,exp:"Dictionary = key-value pairs."},
    {q:"append() does:",opts:["Removes last","Adds at beginning","Adds at end","Sorts"],ans:2,exp:"append() adds to end."},
    {q:"Exception handling keyword:",opts:["catch","error","except","handle"],ans:2,exp:"try-except handles exceptions."},
    {q:"Output of print(2**3):",opts:["6","8","9","5"],ans:1,exp:"2**3 = 8."},
    {q:"Method to remove whitespace from ends:",opts:["trim()","strip()","clean()","remove()"],ans:1,exp:"strip() removes leading/trailing whitespace."},
  ],
  "Data Structures":[
    {q:"Data structure following LIFO:",opts:["Queue","Stack","Linked List","Tree"],ans:1,exp:"Stack = LIFO."},
    {q:"Binary Search time complexity:",opts:["O(n)","O(n log n)","O(log n)","O(1)"],ans:2,exp:"Binary Search = O(log n)."},
    {q:"Traversal: Left-Root-Right:",opts:["Preorder","Inorder","Postorder","Level-order"],ans:1,exp:"Inorder = Left-Root-Right."},
    {q:"Height of complete binary tree:",opts:["O(n)","O(log n)","O(n²)","O(1)"],ans:1,exp:"Height = O(log n)."},
    {q:"BFS uses:",opts:["Stack","Queue","Priority Queue","Hash Map"],ans:1,exp:"BFS = Queue."},
    {q:"In circular list, last node points to:",opts:["NULL","Itself","First node","Previous"],ans:2,exp:"Last → First in circular list."},
    {q:"NOT an application of Stack:",opts:["Recursion","Undo operation","BFS traversal","Expression evaluation"],ans:2,exp:"BFS uses Queue, not Stack."},
    {q:"AVL tree is:",opts:["Binary tree","Self-balancing BST","Graph","Heap"],ans:1,exp:"AVL = self-balancing BST."},
    {q:"Bubble Sort worst case:",opts:["O(n)","O(n log n)","O(n²)","O(log n)"],ans:2,exp:"Bubble Sort = O(n²)."},
    {q:"FIFO data structure:",opts:["Stack","Tree","Queue","Graph"],ans:2,exp:"Queue = FIFO."},
    {q:"Hashing for:",opts:["Sorting","O(1) average search","Graph traversal","Tree balancing"],ans:1,exp:"Hashing = O(1) average search."},
  ],
  "Computer Networks":[
    {q:"HTTP at which OSI layer:",opts:["Transport","Network","Application","Data Link"],ans:2,exp:"HTTP = Layer 7 (Application)."},
    {q:"IPv4 address bits:",opts:["16","32","64","128"],ans:1,exp:"IPv4 = 32 bits."},
    {q:"Connectionless protocol:",opts:["TCP","FTP","UDP","HTTP"],ans:2,exp:"UDP is connectionless."},
    {q:"DNS stands for:",opts:["Domain Name System","Dynamic Network Service","Data Network Server","Domain Node"],ans:0,exp:"DNS = Domain Name System."},
    {q:"Class C subnet mask:",opts:["255.0.0.0","255.255.0.0","255.255.255.0","255.255.255.255"],ans:2,exp:"Class C = 255.255.255.0."},
    {q:"Error detection at which layer:",opts:["Physical","Data Link","Network","Transport"],ans:1,exp:"Data Link = error detection."},
    {q:"OSI model has:",opts:["5","6","7","8"],ans:2,exp:"OSI = 7 layers."},
    {q:"TCP ensures delivery via:",opts:["Checksum only","Three-way handshake","Broadcasting","Encryption"],ans:1,exp:"TCP = three-way handshake."},
    {q:"Ring topology:",opts:["Bus","Star","Ring","Mesh"],ans:2,exp:"Ring = devices in circle."},
    {q:"HTTPS port:",opts:["80","21","443","23"],ans:2,exp:"HTTPS = port 443."},
    {q:"Bandwidth measured in:",opts:["Watts","Decibels","Bits per second","Hertz"],ans:2,exp:"Bandwidth = bps."},
  ],
  "Database Management Systems":[
    {q:"SQL stands for:",opts:["Structured Query Language","Simple Query Logic","Standard Query Layer","Stored Query Language"],ans:0,exp:"SQL = Structured Query Language."},
    {q:"Normal form removing transitive dependencies:",opts:["1NF","2NF","3NF","BCNF"],ans:2,exp:"3NF removes transitive dependencies."},
    {q:"ACID 'I' stands for:",opts:["Integrity","Isolation","Indexing","Inheritance"],ans:1,exp:"I = Isolation."},
    {q:"Command to remove a table:",opts:["DELETE","REMOVE","DROP","TRUNCATE"],ans:2,exp:"DROP TABLE removes table permanently."},
    {q:"Foreign Key references:",opts:["Foreign Key","Primary Key","Unique Key","Composite Key"],ans:1,exp:"FK references PK of another table."},
    {q:"JOIN returning all records from both tables:",opts:["INNER JOIN","LEFT JOIN","RIGHT JOIN","FULL OUTER JOIN"],ans:3,exp:"FULL OUTER JOIN returns all records."},
    {q:"Index is used for:",opts:["Backup","Faster search","Encryption","Normalization"],ans:1,exp:"Index improves search speed."},
    {q:"NoSQL database:",opts:["MySQL","Oracle","MongoDB","PostgreSQL"],ans:2,exp:"MongoDB is NoSQL."},
    {q:"VIEW in SQL is:",opts:["Physical table","Virtual table from query","Backup table","Index"],ans:1,exp:"VIEW = virtual table from SELECT."},
    {q:"HAVING clause used with:",opts:["WHERE","GROUP BY","ORDER BY","JOIN"],ans:1,exp:"HAVING filters GROUP BY results."},
    {q:"Deadlock means:",opts:["Server crash","Two transactions waiting for each other","Data corruption","None"],ans:1,exp:"Deadlock = mutual waiting between transactions."},
  ],
  "Applied Mathematics":[
    {q:"Laplace transform of 1:",opts:["1/s","s","1","1/s²"],ans:0,exp:"L{1} = 1/s."},
    {q:"Rank of zero matrix:",opts:["1","0","Undefined","n"],ans:1,exp:"Zero matrix rank = 0."},
    {q:"Eigenvalue of identity matrix:",opts:["0","1","-1","Undefined"],ans:1,exp:"Identity matrix eigenvalues = 1."},
    {q:"Fourier series represents:",opts:["Polynomial","Periodic function","Linear function","Random"],ans:1,exp:"Fourier series = periodic functions."},
    {q:"Order of d²y/dx² + dy/dx = 0:",opts:["1","2","3","0"],ans:1,exp:"Highest derivative = 2."},
    {q:"Correlation coefficient range:",opts:["0 to 1","-1 to 0","-1 to 1","0 to infinity"],ans:2,exp:"r ∈ [-1, 1]."},
    {q:"Z-transform used for:",opts:["Continuous signals","Discrete signals","Analog circuits","None"],ans:1,exp:"Z-transform = discrete-time analysis."},
    {q:"Singular matrix has determinant:",opts:["1","-1","0","Infinity"],ans:2,exp:"Singular matrix: det = 0."},
    {q:"Regression analysis used to:",opts:["Find correlation","Predict variable relationships","Sort data","None"],ans:1,exp:"Regression predicts variable relationships."},
    {q:"B(m,n) = B(n,m) shows Beta function is:",opts:["Commutative","Associative","Distributive","None"],ans:0,exp:"Beta function is symmetric/commutative."},
  ],
  "Operating Systems":[
    {q:"Scheduling for shortest job:",opts:["FCFS","Round Robin","SJF","Priority"],ans:2,exp:"SJF = Shortest Job First."},
    {q:"Deadlock four conditions:",opts:["Preemption Starvation Aging Priority","Mutual Exclusion Hold-Wait No-Preemption Circular-Wait","Scheduling Paging Segmentation Swapping","None"],ans:1,exp:"Mutual Exclusion, Hold & Wait, No Preemption, Circular Wait."},
    {q:"Virtual memory technique:",opts:["Caching","Paging","Buffering","Spooling"],ans:1,exp:"Paging extends RAM."},
    {q:"RTOS used for:",opts:["Desktop","Time-critical embedded systems","Cloud","Gaming"],ans:1,exp:"RTOS for time-critical tasks."},
    {q:"Semaphore used for:",opts:["Memory","Process synchronization","Scheduling","I/O"],ans:1,exp:"Semaphore = process synchronization."},
    {q:"NOT a CPU scheduling algorithm:",opts:["FCFS","Round Robin","Banker's Algorithm","SJF"],ans:2,exp:"Banker's = deadlock avoidance, not scheduling."},
    {q:"Thrashing means:",opts:["CPU idle","Excessive paging","Memory leak","Process crash"],ans:1,exp:"Thrashing = excessive swapping."},
    {q:"PCB stands for:",opts:["Process Control Block","Program Counter Buffer","Processor Cache Block","None"],ans:0,exp:"PCB = Process Control Block."},
    {q:"Allocation avoiding fragmentation:",opts:["First Fit","Best Fit","Worst Fit","Paging"],ans:3,exp:"Paging eliminates external fragmentation."},
    {q:"fork() system call:",opts:["Terminates process","Creates child process","Schedules","None"],ans:1,exp:"fork() creates child process."},
  ],
  "Core Java":[
    {q:"Java compiles to:",opts:["Machine Code","Native Code","Bytecode","Assembly"],ans:2,exp:"Java → Bytecode."},
    {q:"Keyword preventing overriding:",opts:["static","abstract","final","private"],ans:2,exp:"final prevents overriding."},
    {q:"Default int value in Java:",opts:["null","0","undefined","1"],ans:1,exp:"Default int = 0."},
    {q:"JVM stands for:",opts:["Java Variable Machine","Java Virtual Machine","Java Visual Manager","Just VM"],ans:1,exp:"JVM = Java Virtual Machine."},
    {q:"Interface for creating thread:",opts:["Serializable","Runnable","Comparable","Iterable"],ans:1,exp:"Implement Runnable, override run()."},
    {q:"Encapsulation means:",opts:["Inheriting","Hiding implementation","Overloading","Multiple objects"],ans:1,exp:"Encapsulation = hiding internal details."},
    {q:"Java exception handling:",opts:["try-catch","begin-rescue","try-except","try-handle"],ans:0,exp:"Java uses try-catch-finally."},
    {q:"Collection allowing duplicates:",opts:["Set","Map","List","None"],ans:2,exp:"List allows duplicates."},
    {q:"'super' keyword refers to:",opts:["Current class","Parent class","Interface","Static"],ans:1,exp:"super = parent class."},
    {q:"String in Java is:",opts:["Primitive","Mutable class","Immutable class","Interface"],ans:2,exp:"String is immutable."},
    {q:"NOT a Java access modifier:",opts:["public","private","protected","virtual"],ans:3,exp:"'virtual' is C++ keyword, not Java."},
  ],
  "Introduction to Embedded Systems":[
    {q:"Embedded system is:",opts:["General purpose computer","Dedicated computer for specific task","Gaming console","Server"],ans:1,exp:"Embedded = dedicated for specific function."},
    {q:"Example of embedded system:",opts:["Desktop PC","Laptop","Washing machine controller","Gaming PC"],ans:2,exp:"Washing machine has embedded controller."},
    {q:"RTOS stands for:",opts:["Real Time Operating System","Remote Transfer OS","Random Task OS","None"],ans:0,exp:"RTOS = Real-Time Operating System."},
    {q:"GPIO stands for:",opts:["General Purpose Input Output","Graphical Processing IO","Global Protocol IO","None"],ans:0,exp:"GPIO = General Purpose Input/Output."},
    {q:"Flash memory stores:",opts:["Temporary data","Program code","Cache data","Video only"],ans:1,exp:"Flash stores program code."},
    {q:"Watchdog timer used for:",opts:["Time measurement","System recovery from failure","Graphics","Network"],ans:1,exp:"Watchdog resets system if stuck."},
    {q:"PWM stands for:",opts:["Pulse Width Modulation","Power Width Module","Pulse Wave Management","None"],ans:0,exp:"PWM = Pulse Width Modulation."},
    {q:"ADC converts:",opts:["Analog to Digital","Digital to Analog","ASCII to Digital","None"],ans:0,exp:"ADC = Analog-to-Digital Converter."},
    {q:"Common embedded bus protocol:",opts:["HTTP","I2C","FTP","SMTP"],ans:1,exp:"I2C is common in embedded systems."},
    {q:"Interrupt means:",opts:["System shutdown","Pause main task for urgent event","Memory error","Network fail"],ans:1,exp:"Interrupt handles high-priority event."},
  ],
  "Computer Oriented Statistical Techniques":[
    {q:"Mean of 2,4,6,8,10:",opts:["5","6","7","8"],ans:1,exp:"Mean = 30/5 = 6."},
    {q:"Not affected by extreme values:",opts:["Mean","Median","Mode","Range"],ans:1,exp:"Median is not affected by outliers."},
    {q:"Standard deviation measures:",opts:["Central tendency","Spread of data","Correlation","Regression"],ans:1,exp:"SD = spread/dispersion."},
    {q:"r = 0 means:",opts:["Perfect positive","Perfect negative","No correlation","Strong"],ans:2,exp:"r=0 = no linear correlation."},
    {q:"Chi-square test for:",opts:["Means","Independence of attributes","Regression","None"],ans:1,exp:"Chi-square tests independence."},
    {q:"Probability of impossible event:",opts:["1","0.5","0","-1"],ans:2,exp:"Impossible event probability = 0."},
    {q:"Normal distribution called:",opts:["Poisson","Bell curve","Binomial","Uniform"],ans:1,exp:"Normal distribution = bell curve."},
    {q:"Variance =",opts:["SD squared","Mean","Median","Range/2"],ans:0,exp:"Variance = σ²."},
    {q:"Measure of central tendency:",opts:["Range","Variance","Mode","Standard Deviation"],ans:2,exp:"Mode is central tendency measure."},
    {q:"Regression minimizes:",opts:["Sum of errors","Sum of squared errors","Max error","None"],ans:1,exp:"Least squares minimizes sum of squared errors."},
  ],
  "Software Engineering":[
    {q:"SDLC stands for:",opts:["Software Design Life Code","System Development Life Cycle","Software Development Life Cycle","System Data Logic Cycle"],ans:2,exp:"SDLC = Software Development Life Cycle."},
    {q:"Spiral model combines:",opts:["Waterfall only","Iterative + Risk analysis","Agile + Testing","None"],ans:1,exp:"Spiral = Iterative + Risk analysis."},
    {q:"Use case diagram part of:",opts:["ER Diagrams","UML","DFD","Flowcharts"],ans:1,exp:"UML includes use case diagrams."},
    {q:"Testing for user requirements:",opts:["Unit","Integration","System","Acceptance"],ans:3,exp:"Acceptance Testing = user requirements."},
    {q:"Cohesion refers to:",opts:["Module coupling","Relatedness within module","Module count","Dependencies"],ans:1,exp:"High cohesion = related functions in module."},
    {q:"Black box testing focuses on:",opts:["Internal code","Input/Output behavior","Database","Server"],ans:1,exp:"Black box = I/O without knowing internals."},
    {q:"Incremental model delivers:",opts:["Waterfall","Increments/versions","V-Model","RAD"],ans:1,exp:"Incremental delivers in versions."},
    {q:"SRS stands for:",opts:["Software Requirement Specification","System Resource Summary","Software Runtime","None"],ans:0,exp:"SRS = Software Requirement Specification."},
    {q:"Coupling measures:",opts:["Module size","Module interdependency","Code quality","Coverage"],ans:1,exp:"Coupling = dependency between modules."},
    {q:"Regression testing done after:",opts:["First build","Code changes","DB migration","UI design"],ans:1,exp:"Regression after code changes."},
  ],
  "Computer Graphics and Animation":[
    {q:"DDA stands for:",opts:["Digital Differential Analyzer","Data Drawing Algorithm","Direct Display Approach","None"],ans:0,exp:"DDA = Digital Differential Analyzer (line algorithm)."},
    {q:"Bresenham's algorithm draws:",opts:["3D objects","Lines/circles efficiently","Color fills","Animation"],ans:1,exp:"Bresenham draws lines/circles with integer arithmetic."},
    {q:"RGB stands for:",opts:["Red Green Blue","Red Gray Blue","Real Graphical Base","None"],ans:0,exp:"RGB = Red, Green, Blue."},
    {q:"Transformation that changes size:",opts:["Translation","Rotation","Scaling","Shearing"],ans:2,exp:"Scaling changes object size."},
    {q:"Translation means:",opts:["Rotation","Moving to new position","Scaling","Color change"],ans:1,exp:"Translation moves object position."},
    {q:"Homogeneous coordinates used for:",opts:["Color representation","Matrix transformations","Sound","None"],ans:1,exp:"Homogeneous coords simplify transformations."},
    {q:"Frame rate measured in:",opts:["Pixels","Bytes","FPS","Milliseconds"],ans:2,exp:"FPS = Frames Per Second."},
    {q:"Clipping removes:",opts:["Colors","Objects outside view window","Textures","Lighting"],ans:1,exp:"Clipping removes portions outside viewing area."},
    {q:"3D projection type:",opts:["Fourier","Perspective","Bitmap","Raster"],ans:1,exp:"Perspective simulates human eye view."},
    {q:"Raster scan displays as:",opts:["Vector lines","Grid of pixels","3D model","Waveform"],ans:1,exp:"Raster = grid of pixels."},
  ],
  "Software Project Management":[
    {q:"WBS stands for:",opts:["Work Breakdown Structure","Work Based System","Weekly Build Schedule","None"],ans:0,exp:"WBS = Work Breakdown Structure."},
    {q:"Gantt chart used for:",opts:["Risk analysis","Project scheduling/timeline","Cost estimation","None"],ans:1,exp:"Gantt = project schedule visualization."},
    {q:"CPM identifies:",opts:["Team members","Longest path (critical path)","Budget","Risk"],ans:1,exp:"CPM finds the critical path."},
    {q:"PERT stands for:",opts:["Program Evaluation Review Technique","Project Estimation Review Tool","None","Process Engineering Review"],ans:0,exp:"PERT = Program Evaluation and Review Technique."},
    {q:"Risk in project means:",opts:["Certain problem","Potential future problem","Past issue","Budget"],ans:1,exp:"Risk = potential future problem."},
    {q:"Scope creep means:",opts:["Smaller project","Uncontrolled scope growth","Team expansion","None"],ans:1,exp:"Scope creep = uncontrolled additions."},
    {q:"Agile focuses on:",opts:["Documentation","Iterative development + customer collaboration","Fixed planning","None"],ans:1,exp:"Agile = iterative + collaboration."},
    {q:"Milestone is:",opts:["A risk","Significant project checkpoint","Team member","Budget"],ans:1,exp:"Milestone = significant achievement/deadline."},
    {q:"Project baseline is:",opts:["Initial approved plan","Final deliverable","Team roster","None"],ans:0,exp:"Baseline = original approved plan."},
    {q:"EVM measures:",opts:["Team performance","Project vs plan performance","Customer satisfaction","None"],ans:1,exp:"EVM = project performance vs baseline."},
  ],
  "Internet of Things (IoT)":[
    {q:"IoT stands for:",opts:["Internet of Technology","Internet of Things","Internal Object Transfer","None"],ans:1,exp:"IoT = Internet of Things."},
    {q:"Common IoT protocol:",opts:["HTTP only","MQTT","FTP","SMTP"],ans:1,exp:"MQTT is widely used in IoT."},
    {q:"IoT devices use:",opts:["Desktop CPU","Server GPU","Microcontroller","Mainframe"],ans:2,exp:"IoT uses microcontrollers."},
    {q:"NOT an IoT application:",opts:["Smart home","Health monitoring","Traditional telephone","Smart farming"],ans:2,exp:"Traditional telephone is not IoT."},
    {q:"Actuator used to:",opts:["Sense environment","Take physical action","Store data","Communicate"],ans:1,exp:"Actuator = physical action (motor, valve)."},
    {q:"Sensor used to:",opts:["Control devices","Measure physical parameters","Store data","Connect internet"],ans:1,exp:"Sensor measures physical environment."},
    {q:"Cloud in IoT for:",opts:["Local processing","Data storage and processing","Sensor reading","None"],ans:1,exp:"Cloud = scalable storage/processing."},
    {q:"Edge computing means:",opts:["Cloud processing","Processing near data source","Central server","None"],ans:1,exp:"Edge computing = near device/source."},
    {q:"IPv6 important for IoT because:",opts:["Faster","More IP addresses","Cheaper","None"],ans:1,exp:"IPv6 has more addresses for billions of IoT devices."},
    {q:"Smart IoT wearable:",opts:["Desktop monitor","Smartwatch","Traditional watch","TV remote"],ans:1,exp:"Smartwatch is IoT wearable."},
  ],
  "Artificial Intelligence":[
    {q:"Complete and optimal search for unit-cost:",opts:["DFS","BFS","Hill Climbing","A*"],ans:1,exp:"BFS is complete and optimal."},
    {q:"Turing Test tests:",opts:["Processing Speed","Machine Intelligence","Memory","Networking"],ans:1,exp:"Turing Test = machine intelligence."},
    {q:"AI agent:",opts:["Software bug","Perceives environment, takes actions","Database","Compiler"],ans:1,exp:"Agent = perceives + acts."},
    {q:"Game playing AI algorithm:",opts:["Dijkstra","BFS","Minimax","A*"],ans:2,exp:"Minimax for two-player games."},
    {q:"A* Search function:",opts:["f(n)=g(n)+h(n)","f(n)=g(n)*h(n)","f(n)=h(n)-g(n)","f(n)=g(n)/h(n)"],ans:0,exp:"A* = g(n) + h(n)."},
    {q:"Knowledge representation technique:",opts:["Sorting","Semantic Networks","Hashing","None"],ans:1,exp:"Semantic Networks represent knowledge."},
    {q:"ML is subset of:",opts:["Data Science only","Artificial Intelligence","Statistics only","Programming"],ans:1,exp:"ML is subset of AI."},
    {q:"Expert system uses:",opts:["Neural networks","Knowledge base + Inference engine","Deep learning","None"],ans:1,exp:"Expert system = KB + Inference engine."},
    {q:"NLP deals with:",opts:["Image processing","Human language understanding","Robot motion","None"],ans:1,exp:"NLP = natural language processing."},
    {q:"NOT a search strategy:",opts:["BFS","DFS","A*","TCP"],ans:3,exp:"TCP is a network protocol."},
  ],
  "Advanced Web Programming":[
    {q:"AJAX stands for:",opts:["Asynchronous JavaScript And XML","Advanced Java And XML","Async Java Application XML","None"],ans:0,exp:"AJAX = Asynchronous JavaScript And XML."},
    {q:"REST POST method used to:",opts:["Retrieve","Create resource","Update","Delete"],ans:1,exp:"POST = create new resource."},
    {q:"JSON stands for:",opts:["JavaScript Object Notation","Java Source Object Node","JavaScript Online Network","None"],ans:0,exp:"JSON = JavaScript Object Notation."},
    {q:"Node.js uses which engine:",opts:["SpiderMonkey","Chakra","V8","Gecko"],ans:2,exp:"Node.js = Google V8 engine."},
    {q:"JavaScript framework:",opts:["Django","Laravel","React","Flask"],ans:2,exp:"React is JS framework."},
    {q:"MVC stands for:",opts:["Model View Controller","Main View Core","Module Vertical Component","None"],ans:0,exp:"MVC = Model-View-Controller."},
    {q:"NOT valid HTTP method:",opts:["GET","POST","SEND","DELETE"],ans:2,exp:"SEND is not valid. Use GET, POST, PUT, DELETE."},
    {q:"Cookie stores:",opts:["Server data","Client-side session data","Encrypted data","None"],ans:1,exp:"Cookies store data on client browser."},
    {q:"Common DB with Node.js:",opts:["Oracle","MongoDB","DB2","Sybase"],ans:1,exp:"MongoDB commonly used with Node.js."},
    {q:"npm stands for:",opts:["Node Package Manager","New Program Module","Network Protocol Manager","None"],ans:0,exp:"npm = Node Package Manager."},
  ],
  "Linux System Administration":[
    {q:"Command to list files:",opts:["dir","list","ls","show"],ans:2,exp:"ls lists files in Linux."},
    {q:"Root user UID:",opts:["1","0","999","100"],ans:1,exp:"Root UID = 0."},
    {q:"chmod 755 =",opts:["rwxr-xr-x","rwxrwxrwx","rw-r--r--","rwx------"],ans:0,exp:"755 = rwxr-xr-x."},
    {q:"Command to change file ownership:",opts:["chmod","chown","chgrp","chfile"],ans:1,exp:"chown changes ownership."},
    {q:"ps command shows:",opts:["Print string","Running processes","Power system","None"],ans:1,exp:"ps shows running processes."},
    {q:"File with user account info:",opts:["/etc/shadow","/etc/passwd","/etc/group","/home/user"],ans:1,exp:"/etc/passwd has user accounts."},
    {q:"cron used for:",opts:["Real-time tasks","Scheduled recurring tasks","Network config","Backup only"],ans:1,exp:"cron schedules recurring tasks."},
    {q:"Command for disk usage:",opts:["ls","df","du","dd"],ans:1,exp:"df shows disk space usage."},
    {q:"grep used to:",opts:["Copy files","Search text patterns","Remove files","None"],ans:1,exp:"grep searches text patterns."},
    {q:"Signal to terminate process:",opts:["SIGSTOP","SIGHUP","SIGKILL","SIGINT"],ans:2,exp:"SIGKILL forcefully terminates."},
  ],
  "Enterprise Java":[
    {q:"JEE stands for:",opts:["Java Enterprise Edition","Java Extended Environment","Java Execution Engine","None"],ans:0,exp:"JEE = Java Enterprise Edition."},
    {q:"Servlet used for:",opts:["GUI development","Handling HTTP requests","DB connection only","None"],ans:1,exp:"Servlet handles HTTP requests."},
    {q:"JSP stands for:",opts:["Java Server Pages","Java Simple Program","Java Script Pages","None"],ans:0,exp:"JSP = Java Server Pages."},
    {q:"EJB stands for:",opts:["Enterprise Java Beans","Extended Java Base","External Java Build","None"],ans:0,exp:"EJB = Enterprise JavaBeans."},
    {q:"Hibernate is used for:",opts:["Web development","ORM","Security","Testing"],ans:1,exp:"Hibernate = ORM for Java."},
    {q:"JNDI stands for:",opts:["Java Naming and Directory Interface","Java Network Data Interface","None","Java Node Directory"],ans:0,exp:"JNDI = Java Naming and Directory Interface."},
    {q:"@RestController annotation in Spring:",opts:["@Component","@Service","@RestController","@Repository"],ans:2,exp:"@RestController marks REST API controller."},
    {q:"SOAP stands for:",opts:["Simple Object Access Protocol","Secure Object Application","System Object API","None"],ans:0,exp:"SOAP = Simple Object Access Protocol."},
    {q:"Java build tool:",opts:["npm","Maven","pip","composer"],ans:1,exp:"Maven = Java build/dependency tool."},
    {q:"Connection pooling improves:",opts:["UI performance","DB connection efficiency","Security","None"],ans:1,exp:"Connection pooling reuses DB connections."},
  ],
  "Next Generation Technologies":[
    {q:"Blockchain is:",opts:["Centralized database","Distributed ledger","Social media","Cloud storage"],ans:1,exp:"Blockchain = distributed ledger."},
    {q:"AR stands for:",opts:["Artificial Reality","Augmented Reality","Advanced Reality","None"],ans:1,exp:"AR = Augmented Reality."},
    {q:"5G offers:",opts:["Slower speeds","Higher bandwidth lower latency","No improvement","Less coverage"],ans:1,exp:"5G = higher bandwidth, lower latency."},
    {q:"Quantum computing uses:",opts:["Binary bits","Qubits","Analog signals","None"],ans:1,exp:"Quantum computers use qubits."},
    {q:"DevOps combines:",opts:["Design and Testing","Development and Operations","Data and Operations","None"],ans:1,exp:"DevOps = Dev + Ops."},
    {q:"Microservices means:",opts:["One large app","Small independent services","Cloud only","None"],ans:1,exp:"Microservices = small independent deployable services."},
    {q:"Docker used for:",opts:["Version control","Containerization","Database management","None"],ans:1,exp:"Docker = containerization."},
    {q:"Kubernetes used for:",opts:["Frontend development","Container orchestration","Database design","None"],ans:1,exp:"Kubernetes = container orchestration."},
    {q:"AI/ML being used in:",opts:["Healthcare only","Finance only","Almost all industries","Manufacturing only"],ans:2,exp:"AI/ML = all industries."},
    {q:"Edge computing processes data:",opts:["Only in cloud","Near data source","Central servers","None"],ans:1,exp:"Edge = near source."},
  ],
  "Software Quality Assurance":[
    {q:"SQA stands for:",opts:["Software Quality Assurance","System Query Analysis","Software Query Assurance","None"],ans:0,exp:"SQA = Software Quality Assurance."},
    {q:"Testing individual functions:",opts:["Integration Testing","System Testing","Unit Testing","Acceptance"],ans:2,exp:"Unit Testing = individual functions."},
    {q:"Software metric measures:",opts:["Cost only","Quality attributes","Hardware speed","Network bandwidth"],ans:1,exp:"Metrics measure quality attributes."},
    {q:"CMM stands for:",opts:["Capability Maturity Model","Code Management Method","Central Memory Module","None"],ans:0,exp:"CMM = Capability Maturity Model."},
    {q:"Static testing technique:",opts:["Unit Testing","Code Review","Integration Testing","System Testing"],ans:1,exp:"Code Review = static testing."},
    {q:"Black box testing:",opts:["Internal code","Input/Output behavior","Database","Server"],ans:1,exp:"Black box = I/O behavior."},
    {q:"ISO 9001 related to:",opts:["Network security","Quality management systems","Database design","AI"],ans:1,exp:"ISO 9001 = quality management."},
    {q:"Regression testing done after:",opts:["First build","Code changes","DB migration","UI design"],ans:1,exp:"Regression after code changes."},
    {q:"Defect density =",opts:["Number of developers","Defects per unit size","Server load","Test cases"],ans:1,exp:"Defect density = defects per KLOC."},
    {q:"V-Model pairs each dev phase with:",opts:["Budget","Testing phase","Design","Deployment"],ans:1,exp:"V-Model = dev phase + testing phase."},
    {q:"Alpha testing done by:",opts:["End users","Internal development team","External users","None"],ans:1,exp:"Alpha testing = internal team."},
  ],
  "Business Intelligence":[
    {q:"BI stands for:",opts:["Business Intelligence","Binary Input","Base Infrastructure","None"],ans:0,exp:"BI = Business Intelligence."},
    {q:"Data warehouse used for:",opts:["Online transactions","Analytical reporting","Real-time updates","None"],ans:1,exp:"Data warehouse = analytics and reporting."},
    {q:"ETL stands for:",opts:["Extract Transform Load","Export Table List","Edit Transfer Log","None"],ans:0,exp:"ETL = Extract, Transform, Load."},
    {q:"OLAP stands for:",opts:["Online Analytical Processing","Online Application Protocol","Offline Logical Analysis","None"],ans:0,exp:"OLAP = Online Analytical Processing."},
    {q:"Data mart is:",opts:["Large data warehouse","Subject-specific data warehouse subset","Data backup","None"],ans:1,exp:"Data mart = focused data warehouse."},
    {q:"KPI stands for:",opts:["Key Performance Indicator","Key Process Integration","Knowledge Processing Interface","None"],ans:0,exp:"KPI = Key Performance Indicator."},
    {q:"BI Dashboard is:",opts:["Car dashboard","Visual display of key metrics","Database interface","None"],ans:1,exp:"Dashboard = visual key metrics display."},
    {q:"Data mining used to:",opts:["Delete data","Discover patterns in large datasets","Backup data","None"],ans:1,exp:"Data mining = pattern discovery."},
    {q:"Tableau is a:",opts:["Programming language","BI visualization tool","Database","OS"],ans:1,exp:"Tableau = BI visualization tool."},
    {q:"Drill-down in OLAP:",opts:["Higher level data","More detailed data","Delete data","None"],ans:1,exp:"Drill-down = summary to detail."},
  ],
  "Cyber Laws and IT Security":[
    {q:"IT Act 2000 deals with:",opts:["Income tax","Cybercrime and e-commerce","Traffic rules","None"],ans:1,exp:"IT Act 2000 = cybercrime + e-commerce framework."},
    {q:"Phishing is:",opts:["Legitimate email","Fraudulent credential stealing","Virus","None"],ans:1,exp:"Phishing = fraudulent info stealing."},
    {q:"Encryption converts plaintext to:",opts:["More plaintext","Ciphertext","Binary","None"],ans:1,exp:"Encryption = plaintext → ciphertext."},
    {q:"SSL/TLS provides:",opts:["Email service","Secure encrypted communication","File storage","None"],ans:1,exp:"SSL/TLS = encrypted communication."},
    {q:"Firewall used to:",opts:["Speed internet","Monitor and control network traffic","Store data","None"],ans:1,exp:"Firewall = network traffic monitoring."},
    {q:"DDoS means:",opts:["Distributed Denial of Service","Data Download of System","Direct Domain Service","None"],ans:0,exp:"DDoS = Distributed Denial of Service."},
    {q:"Digital signature for:",opts:["Physical signing","Verifying authenticity of digital docs","Printing","None"],ans:1,exp:"Digital signature = authentication."},
    {q:"2FA uses:",opts:["Password only","Password + second factor","Biometric only","None"],ans:1,exp:"2FA = password + second verification."},
    {q:"Ransomware is:",opts:["Antivirus","Malware encrypting files for ransom","Firewall","None"],ans:1,exp:"Ransomware encrypts and demands ransom."},
    {q:"IPR stands for:",opts:["Internet Protocol Rights","Intellectual Property Rights","Internal Process Rules","None"],ans:1,exp:"IPR = Intellectual Property Rights."},
  ],
  "IT Service Management (ITSM)":[
    {q:"ITIL stands for:",opts:["IT Infrastructure Library","IT International Law","IT Integration Level","None"],ans:0,exp:"ITIL = IT Infrastructure Library."},
    {q:"SLA stands for:",opts:["Service Level Agreement","System Logic Architecture","Software License Agreement","None"],ans:0,exp:"SLA = Service Level Agreement."},
    {q:"Incident management handles:",opts:["New requests","Unplanned service disruptions","Change planning","Capacity"],ans:1,exp:"Incident management restores service."},
    {q:"Change management ensures:",opts:["More incidents","Controlled changes with minimal risk","Faster deployment","None"],ans:1,exp:"Change management = controlled change."},
    {q:"CMDB stands for:",opts:["Configuration Management Database","Central Module Data Backup","None","Computer Managed DB"],ans:0,exp:"CMDB = Configuration Management Database."},
    {q:"Help desk is part of:",opts:["Change management","Service desk/support","Problem management","None"],ans:1,exp:"Help desk = IT support."},
    {q:"Problem management finds:",opts:["Fix incidents","Root cause to prevent recurrence","Deploy changes","None"],ans:1,exp:"Problem management = root cause analysis."},
    {q:"KPI in ITSM measures:",opts:["Employee count","Service performance vs targets","Hardware count","None"],ans:1,exp:"KPI = service performance."},
    {q:"COBIT framework for:",opts:["IT governance","Programming","Database design","None"],ans:0,exp:"COBIT = IT governance framework."},
    {q:"Availability management ensures:",opts:["Maximum downtime","Services available as agreed","Cost reduction","None"],ans:1,exp:"Availability management = uptime per SLA."},
  ],
  "Security in Computing":[
    {q:"CIA triad stands for:",opts:["Central Intelligence Agency","Confidentiality Integrity Availability","Computer Internet Application","None"],ans:1,exp:"CIA = Confidentiality, Integrity, Availability."},
    {q:"Public key encryption uses:",opts:["One key","Two keys (public+private)","Three keys","No keys"],ans:1,exp:"Asymmetric encryption = key pair."},
    {q:"Hash function produces:",opts:["Variable output","Fixed length output","Encrypted data","None"],ans:1,exp:"Hash = fixed-length output."},
    {q:"SQL Injection is:",opts:["Programming technique","Attack inserting malicious SQL","DB backup","None"],ans:1,exp:"SQL Injection = malicious SQL attack."},
    {q:"VPN stands for:",opts:["Virtual Private Network","Very Public Network","Variable Protocol Network","None"],ans:0,exp:"VPN = Virtual Private Network."},
    {q:"Brute force tries:",opts:["Social engineering","All possible passwords","Phishing","None"],ans:1,exp:"Brute force = tries all combinations."},
    {q:"Zero-day vulnerability:",opts:["Old known bug","Unknown/unpatched vulnerability","Patched bug","None"],ans:1,exp:"Zero-day = unknown, no patch available."},
    {q:"AES stands for:",opts:["Advanced Encryption Standard","Automated Encryption System","Applied Encryption Standard","None"],ans:0,exp:"AES = Advanced Encryption Standard."},
    {q:"Steganography hides:",opts:["Data using encryption","Data within other data","Data in DB","None"],ans:1,exp:"Steganography = hidden data in images/audio."},
    {q:"IDS stands for:",opts:["Intrusion Detection System","Internet Data System","Internal Defense Setup","None"],ans:0,exp:"IDS = Intrusion Detection System."},
  ],
  "Data Science":[
    {q:"Python library for data manipulation:",opts:["NumPy","Pandas","Matplotlib","Scikit-learn"],ans:1,exp:"Pandas = data manipulation."},
    {q:"ETL stands for:",opts:["Extract Transform Load","Export Table List","Edit Transfer Log","None"],ans:0,exp:"ETL = Extract, Transform, Load."},
    {q:"Best chart for variable distribution:",opts:["Pie Chart","Bar Chart","Histogram","Line Chart"],ans:2,exp:"Histogram = frequency distribution."},
    {q:"Correlation coefficient range:",opts:["0 to 1","-1 to 0","-1 to 1","0 to 100"],ans:2,exp:"r ∈ [-1, 1]."},
    {q:"ML library in Python:",opts:["Matplotlib","Pandas","Scikit-learn","Seaborn"],ans:2,exp:"Scikit-learn = ML algorithms."},
    {q:"Data preprocessing includes:",opts:["Model training","Handling missing values + normalization","Visualization","None"],ans:1,exp:"Preprocessing = cleaning + normalization."},
    {q:"Overfitting means:",opts:["Good on new data","Memorized training data","Simple model","None"],ans:1,exp:"Overfitting = memorized, poor generalization."},
    {q:"Scatter plot shows:",opts:["Frequency","Relationship between two variables","Proportions","Trend only"],ans:1,exp:"Scatter = relationship between variables."},
    {q:"Big Data characterized by:",opts:["Small Volume","3 Vs: Volume Velocity Variety","Simple Structure","None"],ans:1,exp:"Big Data = Volume, Velocity, Variety."},
    {q:"Mean imputation replaces missing values with:",opts:["Median","Mode","Column mean","Zero"],ans:2,exp:"Mean imputation = column mean."},
  ],
  "Machine Learning":[
    {q:"Supervised Learning uses:",opts:["Unlabelled data","Labelled data","Reinforcement","No data"],ans:1,exp:"Supervised = labelled data."},
    {q:"Classification algorithm:",opts:["K-Means","Linear Regression","Decision Tree","PCA"],ans:2,exp:"Decision Tree = classification."},
    {q:"Overfitting means:",opts:["Good on test","High bias","Memorized training data","Too simple"],ans:2,exp:"Overfitting = memorized training data."},
    {q:"Sigmoid outputs:",opts:["0 to 1","-1 to 1","0 to infinity","-inf to inf"],ans:0,exp:"Sigmoid ∈ (0,1)."},
    {q:"K in K-Means = number of:",opts:["Features","Clusters","Iterations","Learning rate"],ans:1,exp:"K = clusters."},
    {q:"Training data used to:",opts:["Test model","Learn model parameters","Deploy","None"],ans:1,exp:"Training data = learn parameters."},
    {q:"Confusion matrix shows:",opts:["Data distribution","TP,TN,FP,FN classification performance","Regression error","None"],ans:1,exp:"Confusion matrix = classification performance."},
    {q:"Random Forest is:",opts:["Single tree","Ensemble of decision trees","Linear model","None"],ans:1,exp:"Random Forest = ensemble of trees."},
    {q:"Gradient descent minimizes:",opts:["Accuracy","Loss/cost function","Parameters","None"],ans:1,exp:"Gradient descent minimizes loss."},
    {q:"Cross-validation used to:",opts:["Train faster","Evaluate on different data splits","Visualize","None"],ans:1,exp:"Cross-validation = model evaluation."},
  ],
  "Cloud Computing and Web Services":[
    {q:"IaaS stands for:",opts:["Internet as a Service","Infrastructure as a Service","Information as a Service","None"],ans:1,exp:"IaaS = Infrastructure as a Service."},
    {q:"Cloud exclusive to one organization:",opts:["Public","Private","Hybrid","Community"],ans:1,exp:"Private Cloud = one organization."},
    {q:"REST API uses:",opts:["FTP","SMTP","HTTP","TCP"],ans:2,exp:"REST = HTTP protocol."},
    {q:"AWS stands for:",opts:["Advanced Web Services","Amazon Web Services","Automated Workflow","None"],ans:1,exp:"AWS = Amazon Web Services."},
    {q:"SaaS means:",opts:["Software as a Service","Server as a Service","Storage as a Service","None"],ans:0,exp:"SaaS = Software as a Service."},
    {q:"Virtualization creates:",opts:["Physical hardware","Virtual instances of hardware/software","No hardware","None"],ans:1,exp:"Virtualization = virtual resource instances."},
    {q:"Auto-scaling means:",opts:["Manual management","Automatic resource adjustment on demand","Fixed resources","None"],ans:1,exp:"Auto-scaling = dynamic resource adjustment."},
    {q:"Microsoft Azure is:",opts:["Search engine","Cloud computing platform","Social media","None"],ans:1,exp:"Azure = Microsoft cloud platform."},
    {q:"Serverless computing means:",opts:["No servers","Developers don't manage servers","Offline","None"],ans:1,exp:"Serverless = managed servers by provider."},
    {q:"REST preferred over SOAP because:",opts:["More secure","Simpler, lighter, HTTP-based","Faster encryption","None"],ans:1,exp:"REST = simpler, stateless, HTTP."},
  ],
};
